# -*- coding: utf-8 -*-
"""Transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2xsQ1MvG0atkqF6NGSSYyn1hkMv0AlD
"""

!pip install transformers

from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier('This is the best day in my life.')

classifier(['I am sitting','I am glad to be there in a company','But I am missing my parents a lot'])

classifier = pipeline("zero-shot-classification")
classifier(
    "I am working on new startup idea",
    candidate_labels=["education","politics","business"],
)

generator=pipeline("text-generation")
generator("if I am a cricket player,I will")

generator = pipeline("text-generation")
generator("In this course,we will teach you how to")

generator = pipeline("text-generation",model="distilgpt2")
generator(
    "In this course,we will teach you how to",
    max_length=15,
    num_return_sequences=2,
)

unmasker = pipeline("fill-mask")
unmasker("Machine learning is an application of <mask>,",top_k=3)

ner = pipeline("ner",grouped_entities=True)
ner("I am Shruthi and I work at KGiSl in Coimbatore")

question_answerer= pipeline("question-answering")
question_answerer(
    question = "Who is the father of AI?",
    context="John McCarthy is considered as the father of Artificial Intelligence and Artificial intelligence is used for problem solvind and decision making"
)

summarizer = pipeline("summarization")
summarizer(
    """
    Artificial Intelligence may seem to be a new technology but if we do a bit of research, we will find that it has roots deep in the past. In Greek Mythology, it is said that the concepts of AI were used.


The model of Artificial neurons was first brought forward in 1943 by Warren McCulloch and Walter Pits. After seven years, in 1950, a research paper related to AI was published by Alan Turing which was titled 'Computer Machinery and Intelligence. The term Artificial Intelligence was first coined in 1956 by John McCarthy, who is known as the father of Artificial Intelligence.


To conclude, we can say that Artificial Intelligence will be the future of the world. As per the experts, we won't be able to separate ourselves from this technology as it would become an integral part of our lives shortly. AI would change the way we live in this world. This technology would prove to be revolutionary because it will change our lives for good.
Narrow AI (weak AI): This is designed to perform a specific task with intelligence. It is termed as weak AI because it cannot perform beyond its limitations. It is trained to do a specific task. Some examples of Narrow AI are facial recognition (Siri in Apple phones), speech, and image recognition. IBM’s Watson supercomputer, self-driving cars, playing chess, and solving equations are also some of the examples of weak AI.

General AI (AGI or strong AI): This system can perform nearly every cognitive task as efficiently as humans can do. The main characteristic of general AI is to make a system that can think like a human on its own. This is a long-term goal of many researchers to create such machines.

Super AI: Super AI is a type of intelligence of systems in which machines can surpass human intelligence and can perform any cognitive task better than humans. The main features of strong AI would be the ability to think, reason, solve puzzles, make judgments, plan and communicate on its own. The creation of strong AI might be the biggest revolution in human history.


Artificial Intelligence Type-2
Reactive Machines: These machines are the basic types of AI. Such AI systems focus only on current situations and react as per the best possible action. They do not store memories for future actions. IBM’s deep blue system and Google’s Alpha go are the examples of reactive machines.

Limited Memory: These machines can store data or past memories for a short period of time. Examples are self-driving cars. They can store information to navigate the road, speed, and distance of nearby cars.

Theory of Mind: These systems understand emotions, beliefs, and requirements like humans. These kinds of machines are still not invented and it’s a long-term goal for the researchers to create one.

Self-Awareness: Self-awareness AI is the future of artificial intelligence. These machines can outsmart the humans. If these machines are invented then it can bring a revolution in human society.


Conclusion
Artificial Intelligence will bring a huge revolution in the history of mankind. Human civilization will flourish by amplifying human intelligence with artificial intelligence, as long as we manage to keep the technology beneficial.
""")